######## CATEGORY ROUTES ########

# Получает список всех категорий
GET http://localhost:3000/api/categories HTTP/1.1
###



######## SEARCH ROUTES ########

# Получает список всех найденых публикаций
GET http://localhost:3000/api/search?query=20  HTTP/1.1
###



######## ARTICLE ROUTES ########

# Получает список всех найденых публикаций
GET http://localhost:3000/api/articles  HTTP/1.1
###

# Получает одну публикацию
GET http://localhost:3000/api/articles/Wp1PYi  HTTP/1.1
###

# Удаляет одну публикацию
DELETE http://localhost:3000/api/articles/aGJNQU  HTTP/1.1
###

# Создает новую публикацию
POST http://localhost:3000/api/articles  HTTP/1.1
Content-Type: application/json

{
  "title": "Новинки музыки",
  "announce": "Простые ежедневные упражнения помогут достичь успеха.",
  "fullText": "Тяжело найти качественную музыку",
  "createdDate": "2020-04-17 20:25:31",
  "category": ["Музыка"],
  "comments": []
}
###

# Редактирует публикацию
PUT http://localhost:3000/api/articles/Q_lvXb  HTTP/1.1
Content-Type: application/json

{
  "title": "Новинки автопрома",
  "announce": "Простые ежедневные упражнения помогут достичь успеха.",
  "fullText": "Тяжело найти хороший б/у автомобиль",
  "createdDate": "2020-05-17 20:25:31",
  "category": ["Авто"],
  "comments": []
}
###

# Получает комментарии одной публикации
GET http://localhost:3000/api/articles/Wp1PYi/comments  HTTP/1.1
###

# Удаляет один комментарий из публикации
DELETE http://localhost:3000/api/articles/Wp1PYi/comments/xr1wwd  HTTP/1.1
###

# Добавляет новый комментарий к публикации
POST http://localhost:3000/api/articles/Wp1PYi/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый тестовый комментарий"
}
###
